name: the-ai-assistant-clan

services:
  telegram:
    build:
      dockerfile: docker/external-bridges/telegram/Dockerfile
    image: telegram:latest
    container_name: telegram
    networks:
      - the-network-clan

networks:
  the-network-clan: