[package]
name = "telegram"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { version = "0.1.0", path = "../../shared" }
teloxide = "0.17.0"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
