services:
  alloy:
    image: grafana/alloy:v1.7.5
    container_name: alloy
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    volumes:
      - ./docker/monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - the-network-clan

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./docker/monitoring/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - the-network-clan

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - 3000:3000/tcp
    volumes:
      - ./docker/monitoring/grafana/provisioning/datasources/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml:ro
    networks:
      - the-network-clan
